openapi: 3.0.0
info:
  version: "1.0.0"
  title: API SCCON
  description: >
    # Introdução

    Essa API fornece acesso ao serviço de seleção automática das melhores imagens, retornando os IDs para download.
    O serviço é autenticado, ou seja, necessita de um token de segurança para ser acessado.
    A obtenção deste token de segurança é realizada através do serviço de autenticação.


    **Como usar autenticação JWT**<br/>
    Adicionar header com:<br/>
    - Chave: 'Authorization'<br/>
    - Valor : Bearer {access_token}'

  contact:
    email: plataforma@sccon.com.br

tags:
  - name: Token
    description: Fornece o token de acesso para utilizar os demais serviços.
  - name: Melhores Imagens
    description: Busca dos IDs das melhores imagens.
x-tagGroups:
  - name: Autenticação
    tags:
      - Token
  - name: Imagens
    tags:
      - Melhores Imagens
security:
  - JWT Token: []
paths:
  /auth/token:
    get:
      tags:
        - Token
      summary: Acesso ao token
      security: []
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              examples:
                response:
                  value:
                    - access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnYW1hYWdyaWN1bHR1cmEuY29tLmJyIiwic3ViIjoid2VzbGV5LnNpbHZhQHNjY29uLmNvbS5iciIsIm5hbWUiOiJXZXNsZXkgU2lsdmEiLCJleHAiOjE1OTg5MDQ3OTQ0NTAsImlhdCI6MTU5ODI5OTk5NDQ1MCwicm9sZXMiOlsiTUFOQUdFX1VTRVJTIiwiR0VORVJBVEVfV01TX1NFTEVDVEVEX0lNQUdFUyIsIkRPV05MT0FEX0lNQUdFX0FOQUxZVElDX1NSIiwiTUFOQUdFX09SR0FOSVpBVElPTlMiLCJHRVRfTU9TQUlDX0xJTksiLCJWSUVXIiwiRE9XTkxPQURfSU1BR0VfVklTVUFMIiwiRVhQRVJUX1BGIiwiRE9XTkxPQURfU1RBVFMiLCJET1dOTE9BRF9SQUFfU0hFRVQiLCJET1dOTE9BRF9JTUFHRV9TSEFQRSIsIkFDQ0VTU19EQVNIQk9BUkRfUEYiLCJET1dOTE9BRF9BTEVSVFMiLCJET1dOTE9BRCIsIk1BTkFHRV9DT05UUkFDVFMiLCJET1dOTE9BRF9JTUFHRV9BTkFMWVRJQyIsIkFVVE9NQVRJQ19XTVMiXX0.kpAJYGTXpWrV_QEnVUvC9soKojw-mLKmnVRsh8itst4
                      token_type: Bearer
                      iss: plataforma.sccon.com.br
                      sub: plataforma@sccon.com.br
                      name: Usuário do Serviço
                      exp: 1498742285823
                      iat: 1498655885823
                      roles:
                        - Download
                        - Search
        "401":
          description: Não autorizado
  /best:
    post:
      tags:
        - Melhores Imagens
      summary: Busca
      parameters:
        - name: byClouds
          in: query
          description: Usado para informar se a busca será feita usando o parâmetro de nuvens.
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SceneFilterDTO"
      responses:
        "200":
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BestFeaturesDTO"
        "401":
          description: Não autorizado
servers:
  - url: https://plataforma.sccon.com.br/gama-api
components:
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    Token:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Token"
      required: true
  schemas:
    SceneFilterDTO:
      title: Filtros Imagens
      type: object
      required:
        - sort
        - pageSize
        - permissions
        - providers
      properties:
        sort:
          type: string
          description: Ordenação do resultado
        pageSize:
          type: integer
        providers:
          $ref: "#/components/schemas/Providers"
        startAcquiredDate:
          type: string
          description: Valor inicial para pesquisa por data de aquisição da imagem.
        endAcquiredDate:
          type: string
          description: Valor final para pesquisa por data de aquisição da imagem.
        wkts:
          type: array
          description: Geometria para usar como busca.
          items:
            type: string
        startCloudCover:
          type: number
          description: Valor inicial para pesquisa por porcentagem de preechimento por nuvem. Valores entre 0 e 1
        endCloudCover:
          type: number
          description: Valor final para pesquisa por porcentagem de preechimento por nuvem. Valores entre 0 e 1
        startBlackFill:
          type: number
          description: Valor inicial para pesquisa por porcentagem da imagem com preenchimento de bit do tipo black fill. Valores entre 0 e 1
        endBlackFill:
          type: number
          description: Valor final para pesquisa por porcentagem da imagem com preenchimento de bit do tipo black fill. Valores entre 0 e 1
        satelliteId:
          type: string
        startGSD:
          type: number
          description: Valor inicial para pesquisa por porcentagem de Ground Sample Distance. Valores entre 0 e 1
        endGSD:
          type: number
          description: Valor final para pesquisa por porcentagem de Ground Sample Distance. Valores entre 0 e 1
        stripId:
          type: string
          description: Id da faixa de passagem
        onlySSO:
          type: boolean
          description: Apenas satélites de órbita heliossíncrona
        ids:
          type: array
          items:
            type: string
      example:
        sort: "acquired desc"
        pageSize: 20
        providers:
          - PSScene4Band
        startAcquiredDate: 2017-06-22T00:00:00.000Z
        endAcquiredDate: 2017-06-22T00:00:00.000Z
        wkts:
          - POLYGON ((-52.36083984375 -6.948238638117006, -52.36083984375 -6.555474602201876, -51.96533203125001 -6.555474602201876, -51.96533203125001 -6.948238638117006, -52.36083984375 -6.948238638117006))
        startCloudCover: 0.1
        endCloudCover: 0.4
        startBlackFill: 0
        endBlackFill: 1
        satelliteId: '1018'
        startGSD: 0
        endGSD: 3.9
        stripId: '583548'
        onlySSO: true
        ids:
          - '20200830_120115_79_2277'
          - '20200930_120115_79_2277'
    PermissionType:
      title: Permissão
      type: array
      enum:
        - assets.analytic:download
    Providers:
      title: Fornecedor Imagem
      type: array
      enum:
        - PSScene4Band
    BestFeaturesDTO:
      title: Features
      type: object
      properties:
        area:
          type: number
        areaCovered:
          type: number
        percentCovered:
          type: number
        ids:
          type: array
          description: IDs das imagens que serão usados para download
          items:
            type: string
        features:
          type: array
          items:
            $ref: "#/components/schemas/FeatureDTO"
        geometry:
          type: object
          description: Geometria em GeoJson
        geometryCovered:
          type: object
          description: Geometria em GeoJson
      example:
        links:
          first: "assets/scenes/searches/2d96654a03d9421c9e55d820b65ad6e1/results?_page\u003deyJxdWVyeV9wYXJhbXMiOiB7Il9wYWdlX3NpemUiOiAiMjAiLCAiX3NvcnQiOiAiYWNxdWlyZWQgZGVzYyJ9LCAic29ydF9wcmV2IjogZmFsc2UsICJwYWdlX3NpemUiOiAyMCwgInNvcnRfYnkiOiAiYWNxdWlyZWQiLCAic29ydF9zdGFydCI6IG51bGwsICJzb3J0X2xhc3RfaWQiOiBudWxsLCAic29ydF9kZXNjIjogdHJ1ZX0%3D"
          next: "assets/scenes/searches/2d96654a03d9421c9e55d820b65ad6e1/results?_page\u003deyJxdWVyeV9wYXJhbXMiOiB7Il9wYWdlX3NpemUiOiAiMjAiLCAiX3NvcnQiOiAiYWNxdWlyZWQgZGVzYyJ9LCAic29ydF9wcmV2IjogZmFsc2UsICJwYWdlX3NpemUiOiAyMCwgInNvcnRfYnkiOiAiYWNxdWlyZWQiLCAic29ydF9zdGFydCI6ICIyMDE3LTA2LTI2VDEzOjAxOjMyLjMwNzI2NloiLCAic29ydF9sYXN0X2lkIjogIjIwMTcwNjI2XzEzMDEzMl8xMDAzIiwgInNvcnRfZGVzYyI6IHRydWV9"
        features:
          - id: "20200627_130208_1018"
            enabledDownload: true
            links:
              first: "assets/scenes/searches/2d96654a03d9421c9e55d820b65ad6e1/results?_page\u003deyJxdWVyeV9wYXJhbXMiOiB7Il9wYWdlX3NpemUiOiAiMjAiLCAiX3NvcnQiOiAiYWNxdWlyZWQgZGVzYyJ9LCAic29ydF9wcmV2IjogZmFsc2UsICJwYWdlX3NpemUiOiAyMCwgInNvcnRfYnkiOiAiYWNxdWlyZWQiLCAic29ydF9zdGFydCI6IG51bGwsICJzb3J0X2xhc3RfaWQiOiBudWxsLCAic29ydF9kZXNjIjogdHJ1ZX0%3D"
              next: "assets/scenes/searches/2d96654a03d9421c9e55d820b65ad6e1/results?_page\u003deyJxdWVyeV9wYXJhbXMiOiB7Il9wYWdlX3NpemUiOiAiMjAiLCAiX3NvcnQiOiAiYWNxdWlyZWQgZGVzYyJ9LCAic29ydF9wcmV2IjogZmFsc2UsICJwYWdlX3NpemUiOiAyMCwgInNvcnRfYnkiOiAiYWNxdWlyZWQiLCAic29ydF9zdGFydCI6ICIyMDE3LTA2LTI2VDEzOjAxOjMyLjMwNzI2NloiLCAic29ydF9sYXN0X2lkIjogIjIwMTcwNjI2XzEzMDEzMl8xMDAzIiwgInNvcnRfZGVzYyI6IHRydWV9"
            geometry: "{ \"type\": \"Polygon\", \"coordinates\": [ [ [ -52.2370581663976, -6.988069425605272 ], [ -52.464362657581866, -6.942764027451043 ], [ -52.449494587188845, -6.869489317258247 ], [ -52.22280828403941, -6.914693524213432 ], [ -52.224762899115234, -6.924330746448963 ], [ -52.22419009035033, -6.924444984627958 ], [ -52.2370581663976, -6.988069425605272 ] ] ] } }"
            properties:
              acquired: "2017-06-27T13:02:08.573185Z"
              anomalousPixels: 0.0
              cloudCove:  0.0
              columns: 8896
              epsgCod:  32722
              gsd: 3.9
              instrument: "PS2"
              itemTyp:  "PSScene4Band"
              originX:  338220.0
              originY:  9240438.0
              pixelResolutio:  3.0
              provider: "planetscope"
              published: "2017-06-28T10:48:09Z"
              rows: 4350
              satelliteI:  "1018"
              sunAzimut:  49.4
              sunElevatio:  42.5
              updated: "2017-06-28T10:48:09Z"
              usableDat:  0.0
              viewAngl:  1.1
              stripI:  583548
            permissions:
              - "assets.basic_analytic_rpc_nitf:download"
              - "assets.analytic_xml:download"
        pageSize: 20
        requestId: "123e4567-e89b-12d3-a456-426614174000"
    FeatureDTO:
      title: Feature
      type: object
      properties:
        id:
          type: string
        links:
          $ref: "#/components/schemas/LinksDTO"
        geometry:
          type: string
          description: Em GeoJson
        properties:
          $ref: "#/components/schemas/FeaturePropertiesDTO"
        permissions:
          type: array
          description: Downloads permitidos para a imagem
          items:
            type: string
        enableDownload:
          type: boolean
          description: Se a imagem permite download
    LinksDTO:
      title: Links
      type: object
      properties:
        thumbnail:
          type: string
        tms:
          type: string
        first:
          type: string
        next:
          type: string
        prev:
          type: string
        self:
          type: string
        assets:
          type: string
        activate:
          type: string
    Token:
      title: Token
      type: object
      properties:
        access_token:
          type: string
          readOnly: true
        token_type:
          type: string
          readOnly: true
        iss:
          type: string
          readOnly: true
        sub:
          type: string
          readOnly: true
        name:
          type: string
          readOnly: true
        exp:
          type: number
          readOnly: true
        iat:
          type: number
          readOnly: true
        roles:
          type: array
          enum:
            - Download
            - Search
          description: Permissões do usuário autenticado
          